train:
    seed: 2
    batch_size: 64  # Reduced from 1024 for CAUEEG2 which has larger samples
    n_epochs: 5000
    eval_freq: 50
    num_workers: 10  # Reduced from 25 to avoid memory issues
    experiment: 'DDPM'
    output_dir: '/project/outputs'
    base_path: '/home/stud/timlin/bhome/DiffusionEEG/dataset/CAUEEG2'
    data_root: '/home/stud/timlin/bhome/DiffusionEEG/dataset/CAUEEG2'
    run_dir: 'ldm_caueeg2_4ch_116size'  # Updated to reflect CAUEEG2 dataset and 4 channels
    drop_last: false
    base_lr: 0.0001
    save_every: 50

model:
  params:
    timesteps: 1000
    beta_schedule: "linear"
    linear_start: 0.0015
    linear_end: 0.0195
    loss_type: "l2"
    log_every_t: 200
    clip_denoised: False
    original_elbo_weight: 0.0
    v_posterior: 0.0
    l_simple_weight: 1.0
    parameterization: "eps"
    learn_logvar: False
    logvar_init: 0.0
    unet_config:
      params:
        image_size: 116  # Latent space temporal dimension
        in_channels: 4   # Matches latent_channels from autoencoder
        out_channels: 4  # Matches latent_channels from autoencoder
        model_channels: 64
        attention_resolutions: [4]  # Only at deepest level
        num_res_blocks: 2
        channel_mult: [1,2,4]  # Keep matching AEKL depth pattern
        dropout: 0.0
        conv_resample: True
        num_heads: 1
        use_scale_shift_norm: False
        resblock_updown: True