train:
    seed: 2
    batch_size: 16  # Increased from 8 for better training dynamics
    n_epochs: 5000
    val_interval: 100
    num_workers: 10
    drop_last: false
    base_path: 'data/sleep-edfx'
    output_dir: '/project/outputs'
    run_dir: 'aekl_eeg_caueeg2'  # More descriptive name
    experiment: 'AEKL'
models:
  optimizer_g_lr: 0.0001
  optimizer_d_lr: 0.00001
  adv_weight: 0.005
  kl_weight: 1E-6
  spectral_weight: 1E2  # Increased from 1E1 to 1E2 for better spectral learning

autoencoderkl:
  params:
    spatial_dims: 1
    in_channels: 19
    out_channels: 19
    num_channels: [16, 32, 64, 128]  # Increased capacity for 19-channel data
    latent_channels: 8  # Increased from 4 to reduce bottleneck compression
    num_res_blocks: 2
    norm_num_groups: 4
    attention_levels: [false, false, false, false]  # Added attention at deepest level
    with_encoder_nonlocal_attn: false
    with_decoder_nonlocal_attn: false

patchdiscriminator:
  params:
    spatial_dims: 1
    num_layers_d: 3
    num_channels: 64
    in_channels: 19
    out_channels: 1
    kernel_size: 3
    norm: "BATCH"
    bias: false
    padding: 1