train:
    seed: 2
    batch_size: 16  # Match AEKL batch size
    n_epochs: 5000
    eval_freq: 50
    num_workers: 10
    experiment: 'DDPM'
    output_dir: '/project/outputs'
    base_path: '/home/stud/timlin/bhome/DiffusionEEG/dataset/CAUEEG2'
    data_root: '/home/stud/timlin/bhome/DiffusionEEG/dataset/CAUEEG2'
    run_dir: 'ldm_caueeg2_1000size'  # Updated to reflect new parameters
    drop_last: false
    base_lr: 0.0001
    save_every: 50
    warmup_steps: 1000  # Added warmup for stability

model:
  params:
    timesteps: 1000
    beta_schedule: "linear"
    linear_start: 0.0015
    linear_end: 0.0195
    loss_type: "l2"
    log_every_t: 200
    clip_denoised: True  # Changed to True for stability
    original_elbo_weight: 0.0
    v_posterior: 0.0
    l_simple_weight: 1.0
    parameterization: "eps"
    learn_logvar: False
    logvar_init: 0.0
    unet_config:
      params:
        preserve_size: True  # Add this parameter
        image_size: 125  # Matches the actual dimension needed
        in_channels: 19   
        out_channels: 19  
        model_channels: 125  # Make divisible by 5 for cleaner math
        attention_resolutions: [5, 10]  # Adjusted to be divisible by 5
        num_res_blocks: 2
        channel_mult: [1, 2, 4]  # Removed deepest level to avoid odd dimensions
        dropout: 0.0
        conv_resample: True
        num_heads: 5      # Set to 5 (divisible into 125)
        use_scale_shift_norm: True
        resblock_updown: True