# Configuration for CAUEEG GREEN Classifier

# Data paths
paths:
  user_path: "/home/stud/timlin/bhome/DiffusionEEG"
  data_subdir: "/data"
  bids_subdir: "/caueeg_bids"
  derivatives_subdir: "/derivatives/sovaharmony"
  participants_file: "participants.tsv"

# EEG data configuration
eeg:
  # Expected channel names after preprocessing
  channels: ['FP1', 'F3', 'C3', 'P3', 'O1', 'FP2', 'F4', 'C4', 'P4', 'O2', 
             'F7', 'T3', 'T5', 'F8', 'T4', 'T6', 'FZ', 'CZ', 'PZ']
  # File pattern for preprocessed data
  file_pattern: "{subject}_task-eyesClosed_desc-reject_eeg.fif"

# Dataset configuration
dataset:
  # Number of epochs to use per subject
  n_epochs_per_subject: 20
  # Padding strategy when subjects have fewer epochs
  padding: "repeat"  # Options: "repeat", "zero", null
  # Whether to shuffle epochs
  shuffle: true
  # Random seed for reproducibility
  random_state: 42

# Model architecture
model:
  # Wavelet configuration
  n_freqs: 10  # Number of frequency bands (NOT number of channels!)
  # This creates 10 different wavelets spanning the frequency range
  # Common choices: 5-8 (basic bands), 10-15 (good resolution), 20+ (fine resolution)
  
  kernel_width_s: 0.5  # Wavelet kernel width in seconds
  conv_stride: 5  # Convolution stride
  oct_min: 0  # Minimum frequency in octaves (~1 Hz)
  oct_max: 5.5  # Maximum frequency in octaves (~45 Hz)
  # The 10 frequencies will be evenly spaced between oct_min and oct_max
  
  # SPD layers configuration
  shrinkage_init: -3.0  # Initial shrinkage value
  logref: "logeuclid"  # Reference for log mapping: "identity" or "logeuclid"
  bi_out: [10]  # BiMap output dimensions (reduces spatial dimension from 19 to 10)
  orth_weights: true  # Use orthogonal weights in BiMap
  
  # Neural network configuration
  hidden_dim: [32, 16]  # Hidden layer dimensions
  dropout: 0.5  # Dropout rate
  
  # Data type
  dtype: "float32"  # Options: "float32", "float64"

# Training configuration
training:
  # Number of epochs
  n_epochs: 50
  # Batch size
  batch_size: 32
  # Learning rate
  learning_rate: 1e-3
  # Weight decay (L2 regularization)
  weight_decay: 1e-4
  # Learning rate for wavelet parameters (relative to main lr)
  lr_wavelet: null  # Set to a value like 0.1 to use different lr for wavelets
  # Number of workers for data loading
  num_workers: 4

# Cross-validation configuration
cross_validation:
  # Number of folds
  n_splits: 5
  # Whether to shuffle before splitting
  shuffle: true
  # Random seed for CV splits
  random_state: 42
  # Whether to save predictions
  save_preds: true
  # Checkpoint directory prefix
  ckpt_prefix: "checkpoints/caueeg"

# Label configuration
labels:
  # Column name in participants.tsv
  label_column: "ad_syndrome_3"
  # Label encoding type
  encoding: "one_hot"  # Options: "one_hot", "binary"
  # Expected classes (for validation)
  expected_classes: ["dementia", "hc (+smc)", "mci"]