train:
    seed: 2
    batch_size: 16
    n_epochs: 1000
    val_interval: 100
    num_workers: 25
    drop_last: false
    base_path: 'data/sleep-edfx'
    output_dir: '/project/outputs'
    run_dir: 'aekl_eeg'
    experiment: 'AEKL'
models:
  optimizer_g_lr: 0.005
  optimizer_d_lr: 0.0005
  adv_weight: 0.01
  kl_weight: 1E-9
  disc_lr: 5e-4

autoencoderkl:
  params:
    spatial_dims: 1
    in_channels: 1
    out_channels: 1
    num_channels: [2, 2, 4]
    latent_channels: 1
    num_res_blocks: 2
    norm_num_groups: 1
    attention_levels: [false, false, false]
    with_encoder_nonlocal_attn: false
    with_decoder_nonlocal_attn: false

patchdiscriminator:
  params:
    spatial_dims: 1
    num_layers_d: 3
    num_channels: 64
    in_channels: 1
    out_channels: 1
    kernel_size: 3
    norm: "BATCH"
    bias: false
    padding: 1
