name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.1.3
  - scipy=1.14.1
  - matplotlib=3.9.3
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - pip
  - pip:
    - mne==1.8.0
    - mne-bids==0.16.0
    - mne-connectivity
    - astropy==7.0.0
    - pyprep==0.4.3
    - seaborn==0.13.2
    - cmasher
    - fooof
    - pybids==0.17.2
    - statsmodels==0.14.4
    - sovachronux @ git+https://gitfront.io/r/GRUNECO/4BjKkjJbDxf7/sovachronux.git@31d27aac25f255067c3d210f1a9f0c678a45b356
    - sovaflow @ git+https://gitfront.io/r/GRUNECO/E827iy6c5ads/sovaflow.git@7c0bfe30389671843b2df9cf7aa4931889903703
    - sovareject @ git+https://gitfront.io/r/GRUNECO/8cVYUCpdJGJa/sovareject.git@0b2013b310abba3f444be86f23bf20778f85fad4
    - sovawica @ git+https://github.com/GRUNECO/sovawica.git@362fed4f474870af39d3bf0f08e2c9d48eb21c6b